myFav/config/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
]

myFav/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
  path('', views.main, name='main'),
  path('duruduru', views.duruduru, name='duruduru'),
  path('mochamilk', views.mochamilk, name='mochamilk'),
  path('duruduru/comment', views.comment_duruduru, name='comment_duruduru'),
  path('mochamilk/comment', views.comment_mochamilk, name='comment_mochamilk'),
]

myFav/main/models.py
from django.db import models

# Create your models here.
class Comment_duruduru(models.Model):
  content = models.TextField()
  create_date = models.DateTimeField()

class Comment_mochamilk(models.Model):
  content = models.TextField()
  create_date = models.DateTimeField()

myFav/main/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from .models import Comment_duruduru, Comment_mochamilk
from django.core.paginator import Paginator

# Create your views here.
def main(request):
  return render(request, 'main/main.html')

def duruduru(request):
  page = request.GET.get('page', '1')
  comment_list = Comment_duruduru.objects.order_by('-create_date')
  paginator = Paginator(comment_list, 4)  # 페이지당 4개씩 보여주기
  page_obj = paginator.get_page(page)
  context = {'comment_list': page_obj}
  return render(request, 'main/duruduru.html', context)

def mochamilk(request):
  page = request.GET.get('page', '1')
  comment_list = Comment_mochamilk.objects.order_by('-create_date')
  paginator = Paginator(comment_list, 4)  # 페이지당 4개씩 보여주기
  page_obj = paginator.get_page(page)
  context = {'comment_list': page_obj}
  return render(request, 'main/mochamilk.html', context)

def comment_duruduru(request):
  if request.method == 'POST':
    comment = Comment_duruduru(content=request.POST.get('content'), create_date=timezone.now())
    if len(comment.content) == 0:
      return redirect('main:duruduru')
    comment.save()
  return redirect('main:duruduru')

def comment_mochamilk(request):
  if request.method == 'POST':
    comment = Comment_mochamilk(content=request.POST.get('content'), create_date=timezone.now())
    if len(comment.content) == 0:
      return redirect('main:mochamilk')
    comment.save()
  return redirect('main:mochamilk')

myFav/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">
  <!-- Head -->
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">

    <link rel="stylesheet" href="{% static './css/bootstrap.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, 0.1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static './css/cover.css' %}">
    <link rel="stylesheet" href="{% static './css/carousel.css' %}">
    <link rel="stylesheet" href="{% static './css/carousel.rtl.css' %}">
  </head>

  <!-- Body -->
  <body class="d-flex h-100 text-center text-bg-dark">
    {% block content %}
    {% endblock %}
    <script src="{% static './js/bootstrap.bundle.js' %}"></script>
  </body>
</html>

myFav/templates/main/duruduru.html
{% extends 'base_detail.html' %}
{% load comment_filter %}
{% block content %}
    <div class="d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="header-cover-container mb-auto">
        <div>
          <h3 class="float-md-start mb-0">My Favorite Pet Channel</h3>
          <nav class="nav nav-masthead justify-content-center float-md-end">
            <a class="nav-link fw-bold py-1 px-0" aria-current="page" href="{% url 'main:main' %}">Home</a>
            <a class="nav-link fw-bold py-1 px-0 active" href="{% url 'main:duruduru' %}">DuruDuru</a>
            <a class="nav-link fw-bold py-1 px-0" href="{% url 'main:mochamilk' %}">MochaMilk</a>
          </nav>
        </div>
      </header>
    
      <main class="px-1">

        <!-- START THE FEATURETTES -->
        
        <img src="https://i.postimg.cc/bv9d2M1M/duruduru-main-page.png" class="shadow-lg my-5 rounded-3" alt="hodu_maru" width="100%">
        
        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 lh-base">
            <h2 class="featurette-heading display-6 lh-base fw-bold">Hodu</h2><br>
            <p class="lead fw-light">1. Date of birth : <mark>12/14/2017</mark></p>
            <p class="lead fw-light">2. Gender : <mark>Male</mark></p>
            <figcaption class="blockquote-footer">
              Neutering Finished
            </figcaption>
            <p class="lead fw-light">3. Type : <mark>100% Mixed-Breed</mark></p>
            <p class="lead fw-light">4. Characteristic : <mark>Naive</mark>, <mark>Genial</mark></p>
          </div>
          <div class="col-md-5">
            <span class="shadow-lg"><img src="https://i.postimg.cc/52jsbn7W/hodu.png" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3
            " alt="hodu" width="500px" height="500px"></span>
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading display-6 lh-base fw-bold">Maru</h2><br>
            <p class="lead fw-light">1. Date of birth : <mark>12/14/2017</mark></p>
            <p class="lead fw-light">2. Gender : <mark>Male</mark></p>
            <figcaption class="blockquote-footer">
              Also Neutering Finished
            </figcaption>
            <p class="lead fw-light">3. Type : <mark>100% Mixed-Breed</mark></p>
            <p class="lead fw-light">4. Characteristic : <mark>Easygoing</mark>, <mark>Couch</mark></p>
          </div>
          <div class="col-md-5 order-md-1">
            <span class="shadow-lg"><img src="https://i.postimg.cc/NjgKWj4K/maru.png" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3
              " alt="hodu" width="500px" height="500px"></span>
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette ms-5">
          <div class="col-md-5 order-md-2">
            <h2 class="featurette-heading fw-light lh-1">Youtube Channel "<strong><a href="https://www.youtube.com/@duruduru4512/featured" class="text-decoration-none">DuruDuru</a></strong>"</h2>
            <p class="lead">Find out these adorable guys!</p>  
            <p class="lead">Instagram : <a href="https://www.instagram.com/hodurang_marurang/"><svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16" style="color:aliceblue">
              <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
            </svg></a></p>            
          </div>
          <div class="col-md-3 order-md-1">
            <img src="https://i.postimg.cc/Jzd36DkQ/hodu-1.png" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3
            " alt="" width="500px" height="500px">
          </div>
          <div class="col-md-3 order-md-3">
            <img src="https://i.postimg.cc/j5Y7mzdy/maru-1.png" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3
            " alt="" width="500px" height="500px">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette justify-content-around">
          <div class="col-md-4 align-self-start">
            <h2 class="display-6 lh-base fw-bold">Leave Comments</h2><br>
            <form action="{% url 'main:comment_duruduru' %}" method="post">
              {% csrf_token %}
              <div class="mb-4">
                <textarea class="form-control" name="content" id="content" rows="5c"></textarea>
              </div>
              <input type="submit" class="btn btn-outline-light" value="Leave Comment">
            </form>
          </div>
          <div class="col-md-6 align-self-start">
            <div class="container my-1">
              <table class="table">
                  <thead>
                  <tr class="table-dark">
                      <th>No.</th>
                      <th>Comment</th>
                      <th>Date</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% if comment_list %}
                  {% for comment in comment_list %}
                  <tr>
                    <td>
                      <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                      <p class="text-white fw-4 text-center my-2">{{ comment_list.paginator.count|sub:comment_list.start_index|sub:forloop.counter0|add:1 }}</p>
                    </td>
                    <td>
                      <p class="text-white fw-4 text-center my-2">{{ comment.content }}</p>
                    </td>
                    <td>
                      <p class="text-white fw-4 text-center my-2">{{ comment.create_date }}</p>
                    </td>
                  </tr>
                  {% endfor %}
                  {% else %}
                  <tr>
                      <td colspan="3"><p class="text-white fw-4 text-center my-2">No comments</p></td>
                  </tr>
                  {% endif %}
                  </tbody>
              </table>
              <!-- 페이징처리 시작 -->
              <ul class="pagination justify-content-center">
                  <!-- 이전페이지 -->
                  {% if comment_list.has_previous %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ comment_list.previous_page_number }}">Previous</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Previous</a>
                  </li>
                  {% endif %}
                  <!-- 페이지리스트 -->
                  {% for page_number in comment_list.paginator.page_range %}
                  {% if page_number >= comment_list.number|add:-2 and page_number <= comment_list.number|add:2 %}
                  {% if page_number == comment_list.number %}
                  <li class="page-item active" aria-current="page">
                      <a class="page-link">{{ page_number }}</a>
                  </li>
                  {% else %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                  </li>
                  {% endif %}
                  {% endif %}
                  {% endfor %}
                  <!-- 다음페이지 -->
                  {% if comment_list.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ comment_list.next_page_number }}">Next</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
                  </li>
                  {% endif %}
              </ul>
          </div>
        </div>

        <hr class="featurette-divider">
        
        <!-- /END THE FEATURETTES -->
      </main>

      <footer class="mt-auto mx-auto text-white-50">
        <p>Made by Beomsoon Park</p>
      </footer>
    </div>
{% endblock %}

myFav/templates/main/main.html
{% extends 'base.html' %}
{% block content %}
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="mb-auto">
        <div>
          <h3 class="float-md-start mb-0">My Favorite Pet Channel</h3>
          <nav class="nav nav-masthead justify-content-center float-md-end">
            <a class="nav-link fw-bold py-1 px-0 active" aria-current="page" href="{% url 'main:main' %}">Home</a>
            <a class="nav-link fw-bold py-1 px-0" href="{% url 'main:duruduru' %}">DuruDuru</a>
            <a class="nav-link fw-bold py-1 px-0" href="{% url 'main:mochamilk' %}">MochaMilk</a>
          </nav>
        </div>
      </header>

      <main class="px-1">
        <div class="text-align">
          <img src="https://i.postimg.cc/cJpYhRpy/hodumaru.png" class="shadow-lg my-3 rounded-3 float-md-start" alt="hodu_maru" width="300px" height="200px">
          <img src="https://i.postimg.cc/VkMb6rSK/mochamilk.png" class="shadow-lg my-3 rounded-3 float-md-end" alt="mocha_milk" width="300px" height="200px">
        </div>
        <h1>Welcome to my website</h1>
        <p class="lead">This website is made by <strong>Beomsoon Park</strong>. The channels introduced in this website are chosen by the creater's own favor. Do not make any complaint on my website and these channels.</p>
      </main>

      <footer class="mt-auto text-white-50">
        <p>Made by Beomsoon Park</p>
      </footer>
    </div>
{% endblock %}

myFav/templates/main/mochamilk.html
{% extends 'base_detail.html' %}
{% load comment_filter %}
{% block content %}
    <div class="d-flex w-100 h-100 p-3 mx-auto flex-column">
      <header class="header-cover-container mb-auto">
        <div>
          <h3 class="float-md-start mb-0">My Favorite Pet Channel</h3>
          <nav class="nav nav-masthead justify-content-center float-md-end">
            <a class="nav-link fw-bold py-1 px-0" aria-current="page" href="{% url 'main:main' %}">Home</a>
            <a class="nav-link fw-bold py-1 px-0" href="{% url 'main:duruduru' %}">DuruDuru</a>
            <a class="nav-link fw-bold py-1 px-0 active" href="{% url 'main:mochamilk' %}">MochaMilk</a>
          </nav>
        </div>
      </header>
    
      <main class="px-1">

        <!-- START THE FEATURETTES -->
        
        <img src="https://i.postimg.cc/8Pzzyg0m/mochamilk-main-page.png" class="shadow-lg my-5 rounded-3" alt="mocha_wooyoo" width="100%">
        
        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 lh-base">
            <h2 class="featurette-heading display-6 lh-base fw-bold">Wooyoo</h2><br>
            <p class="lead fw-light">1. Date of birth : <mark>11/7/2016</mark></p>
            <p class="lead fw-light">2. Gender : <mark>Female</mark></p>
            <p class="lead fw-light">3. Type : <mark>Samoyed</mark></p>
            <p class="lead fw-light">4. Characteristic : <mark>Naive</mark>, <mark>Genial</mark></p>
            <p class="lead fw-light">5. She lives in <mark>Toronto, Canada</mark></p>
          </div>
          <div class="col-md-5">
            <span class="shadow-lg"><img src="https://i.postimg.cc/mkhKHjmC/wooyoo.png" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3
            " alt="wooyoo" width="500px" height="500px"></span>
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
          <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading display-6 lh-base fw-bold">Mocha</h2><br>
            <p class="lead fw-light">1. Date of birth : <mark>10/22/2011</mark></p>
            <p class="lead fw-light">2. Gender : <mark>Male</mark></p>
            <figcaption class="blockquote-footer">
              Not known about neutering
            </figcaption>
            <p class="lead fw-light">3. Type : <mark>Pomeranian X Spitz</mark></p>
            <p class="lead fw-light">4. Characteristic : <mark>Sensitive</mark>, sometimes <mark>indifferent</mark></p>
          </div>
          <div class="col-md-5 order-md-1">
            <span class="shadow-lg"><img src="https://i.postimg.cc/G2DXwfgM/mocha.png" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3
              " alt="mocha" width="500px" height="500px"></span>
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette ms-5">
          <div class="col-md-5 order-md-2">
            <h2 class="featurette-heading fw-light lh-1">Youtube Channel "<strong><a href="https://www.youtube.com/@mochamilk" class="text-decoration-none">MochaMilk</a></strong>"</h2>
            <p class="lead">Here are lovely guys!</p>
            <p class="fs-4">Instagram : <a href="https://www.instagram.com/milk_the_samoyed/"><svg xmlns="http://www.w3.org/2000/svg" width="21" height="21" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16" style="color:aliceblue">
              <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
            </svg></a></p>       
          </div>
          <div class="col-md-3 order-md-1">
            <img src="https://i.postimg.cc/QC4mprFd/mochamilk-1.jpg" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3
            " alt="mochamilk_1" width="500px" height="500px">
          </div>
          <div class="col-md-3 order-md-3">
            <img src="https://i.postimg.cc/Pq4j8TGw/mochamilk-2.png" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto rounded-3
            " alt="" width="500px" height="500px">
          </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette justify-content-around">
          <div class="col-md-4 align-self-start">
            <h2 class="display-6 lh-base fw-bold">Leave Comments</h2><br>
            <form action="{% url 'main:comment_mochamilk' %}" method="post">
              {% csrf_token %}
              <div class="mb-4">
                <textarea class="form-control" name="content" id="content" rows="5c"></textarea>
              </div>
              <input type="submit" class="btn btn-outline-light" value="Leave Comment">
            </form>
          </div>
          <div class="col-md-6 align-self-start">
            <div class="container my-1">
              <table class="table">
                  <thead>
                  <tr class="table-dark">
                      <th>No.</th>
                      <th>Comment</th>
                      <th>Date</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% if comment_list %}
                  {% for comment in comment_list %}
                  <tr>
                    <td>
                      <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                      <p class="text-white fw-4 text-center my-2">{{ comment_list.paginator.count|sub:comment_list.start_index|sub:forloop.counter0|add:1 }}</p>
                    </td>
                    <td>
                      <p class="text-white fw-4 text-center my-2">{{ comment.content }}</p>
                    </td>
                    <td>
                      <p class="text-white fw-4 text-center my-2">{{ comment.create_date }}</p>
                    </td>
                  </tr>
                  {% endfor %}
                  {% else %}
                  <tr>
                      <td colspan="3"><p class="text-white fw-4 text-center my-2">No comments</p></td>
                  </tr>
                  {% endif %}
                  </tbody>
              </table>
              <!-- 페이징처리 시작 -->
              <ul class="pagination justify-content-center">
                  <!-- 이전페이지 -->
                  {% if comment_list.has_previous %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ comment_list.previous_page_number }}">Previous</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Previous</a>
                  </li>
                  {% endif %}
                  <!-- 페이지리스트 -->
                  {% for page_number in comment_list.paginator.page_range %}
                  {% if page_number >= comment_list.number|add:-2 and page_number <= comment_list.number|add:2 %}
                  {% if page_number == comment_list.number %}
                  <li class="page-item active" aria-current="page">
                      <a class="page-link">{{ page_number }}</a>
                  </li>
                  {% else %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                  </li>
                  {% endif %}
                  {% endif %}
                  {% endfor %}
                  <!-- 다음페이지 -->
                  {% if comment_list.has_next %}
                  <li class="page-item">
                      <a class="page-link" href="?page={{ comment_list.next_page_number }}">Next</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled">
                      <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
                  </li>
                  {% endif %}
              </ul>
          </div>
        </div>

        <hr class="featurette-divider">
        <!-- END THE FEATURETTES -->
      </main>

      <footer class="mt-auto mx-auto text-white-50 text-center">
        <p>Made by Beomsoon Park</p>
      </footer>
    </div>
{% endblock %}